### PR TITLE
SmartWordlist updates

### PR DESCRIPTION
**Pull request by ravensbane**
I found this tool while looking for a way to recover my password and it was a big help. I knew part of the password and had a general idea of the format, so I used the SmartWordlist method to work on figuring it out. Along the way I added some arguments to make it a little more flexible and added multi-threading to handle big dictionaries. Thanks for writing the tool. If you like my additions, perhaps you'll merge them in to your branch. The changes are mostly to the SmartWordlist classes. Changes to the other classes are mostly Eclipse formatting stuff.

Changelog:
- The SmartWordlist method is now multithreaded for increased
performance on multi-core processors.
- The SmartWordlist method now automatically saves its progress every 30
seconds. If the tool is interrupted before it finishes checking all
combinations in the word list it will resume from the last save.
- Added new -firstchars parameter for use with SmartWordlist method.
This parameter allows the user to specify known characters at the start
of the password. For example, if the user knows that the forgotten
password starts with "Apple", the tool can insert "Apple" at the front
of tested passwords.
- Added new -pieces parameter for use with SmartWordlist method. This
parameter allows the user to specify minimum and maximum number of word
pieces to use when building passwords. The tool will start at the first
combination of minimum word pieces and stop at the last combination of
maximum word pieces.

### CODE REVIEW

**Comment by Spoetnic** [comment]
Nice, this is basically the same stuff I added a week ago for my own project :p

**Comment by ravensbane** [comment]
Haha, great minds or something.

**Comment by MaxCamillo** [comment]
Hey ravensbane, thanks for your update ;) I will merge it

**Comment by ravensbane** [comment]
Hope it helps other people who forget their passwords, too.

**Pull request merged**
